apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grafana-deployment-devops
  name: grafana-service-devops
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 32000
  selector:
    app: grafana-deployment-devops
  type: NodePort
status:
  loadBalancer: {}