---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nautilus
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/sysops
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nautilus
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nautilus
  labels:
    app: pod-nautilus
spec:
  containers:
    - name: container-nautilus
      image: httpd:latest
      volumeMounts:
      - mountPath: "/var/www/html"
        name: pv-nautilus
      ports:
        - containerPort: 80
  volumes:
    - name: pv-nautilus
      persistentVolumeClaim:
        claimName: pvc-nautilus
---
apiVersion: v1
kind: Service
metadata:
  name: web-nautilus
spec:
  selector:
    app: pod-nautilus
  ports:
  - nodePort: 30008
    port: 80
    targetPort: 80
  type: NodePort
