---
apiVersion: v1
data:
  ecommerce.txt: NWVjdXIzCg==
kind: Secret
metadata:
  name: ecommerce
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-datacenter
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: ecommerce
  containers:
    - name: secret-container-datacenter
      image: debian:latest
      command: ['sh', '-c', 'sleep 3600']
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/opt/cluster"
